name: flutter_firebase_feature_feedback
description: "A Flutter package that enables developers to collect and manage feature feedback from their users using Firebase. Users can submit feature requests and vote on existing ones."
version: 0.0.1
homepage: https://github.com/Zee-Palm-LLC/flutter_firebase_feature_feedback  
repository: https://github.com/Zee-Palm-LLC/flutter_firebase_feature_feedback 
issue_tracker: https://github.com/Zee-Palm-LLC/flutter_firebase_feature_feedback/issues 

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  provider: ^6.1.2
  shadcn_ui: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.3.2
  fake_cloud_firestore: ^2.4.1+1
  build_runner: ^2.3.3
  
false_secrets:
 - /example/lib/firebase_options.dart

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
